server:
    port: '${port:8080}'
spring:
  datasource:
    url:  '${dbUrl}'
    username: '${dbUser}'
    password: '${dbPassword}'
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        temp:
          # disable load of metadata; takes ages and does not do anything;
          # would fail with exception due to LOB issues anyway
          # https://stackoverflow.com/questions/10075081/hibernate-slow-to-acquire-postgres-connection
          use_jdbc_metadata_defaults: false
  logging:
    level:
      info.kschamer.w1sensorfrontend: 'INFO'